openapi: 3.0.3
info:
  title: Dragon Management API
  description: API для управления коллекцией объектов типа Dragon
  version: 1.0.0
paths:
  /killer/dragon/find-by-cave-depth/{max-or-min}:
    get:
      summary: Найти дракона, живущего в самой глубокой (или мелкой) пещере
      parameters:
        - in: path
          name: max-or-min
          required: true
          schema:
            $ref: '#/components/schemas/CaveSize'
      responses:
        '200':
          description: Объект Dragon
          content:
            application/xml:
              schema:
                $ref: './first_service.yaml#/components/schemas/Dragon'
        '400':
          description: Bag request
          content:
            application/xml:
              schema:
                $ref: './first_service.yaml#/components/schemas/ErrorIQP'
        '404':
          description: Not found
          content:
            application/xml:
              schema:
                $ref: './first_service.yaml#/components/schemas/ErrorDefault'
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: './first_service.yaml#/components/schemas/ErrorISE'
                
  /killer/team/{team-id}/move-to-cave/{cave-id}:
    get:
      summary: Отправить команду убийц драконов в указанную пещеру
      parameters:
        - in: path
          name: team-id
          required: true
          schema:
            type: integer
        - in: path
          name: cave-id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Статус операции по убийству дракона
          content:
            application/xml:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Дракон убит
                    description: Результат операции
                xml:
                  name: result
        '400':
          description: Bag request
          content:
            application/xml:
              schema:
                $ref: './first_service.yaml#/components/schemas/ErrorIQP'
        '404':
          description: Not found
          content:
            application/xml:
              schema:
                $ref: './first_service.yaml#/components/schemas/ErrorDefault'
        '500':
          description: Internal server error
          content:
            application/xml:
              schema:
                $ref: './first_service.yaml#/components/schemas/ErrorISE'

components:
  schemas:
    CaveSize:
      type: string
      enum:
        - MAX
        - MIN
      xml:
        name: caveSize